version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: drkiq
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    restart: always
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - drkiq-redis:/var/lib/redis/data

  drkiq:
    build:
      context: .
    volumes:
      - ./drkiq:/opt/app
    depends_on:
      - postgres
      - redis
    ports:
      - '8010:8010'
    restart: always
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    depends_on:
      - postgres
      - redis
    restart: always
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - drkiq
    restart: always
    ports:
      - '8020:8020'

volumes:
  drkiq-postgres:
  drkiq-redis:
